name: Build Frida Bionic arm64
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip ninja-build
          pip3 install meson

      - name: Configure
        run: |
          python3 tools/ensure-submodules.py
          ./configure --enable-server

      - name: Build Android ARM64
        run: |
          make frida-server-android-arm64 -j$(nproc)
          echo "--- CHECK ---"
          file build/frida-server/android-arm64/frida-server

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: frida-server-android-arm64-bionic
          path: build/frida-server/android-arm64/frida-server
